version: "{build}"

image: Visual Studio 2019

branches:
  only:
    - master
    - release

configuration:
  - release

clone_depth: 100
skip_tags: true
skip_commits:
  files:
    - .bintray.sh
    - .ci-dockerfiles/*
    - .circleci/config.yml
    - .cirrus.yml
    - .gitattributes
    - .gitignore
    - .gitmodules
    - .travis.yml
    - .travis_commands.bash
    - .travis_install.bash
    - .travis_script.bash
    - '**/Dockerfile'
    - LICENSE
    - Makefile
    - Makefile-ponyc
    - release.bash
    - '**/*.md'
    - '**/*.txt'

clone_folder: C:\projects\ponyc

build_script:
  - ps: |
      $ErrorActionPreference = "Stop"
      cd C:\projects\ponyc
      if (!(Test-Path "C:\projects\ponyc\build\libs\bin\llc.exe"))
      {
        & git submodule update --init --recursive
        & C:\projects\ponyc\make.ps1 libs
      }
      $package_commit = git rev-parse --short --verify "HEAD^{commit}"
      $package_version = (Get-Content "VERSION")
      $package_iteration = "$package_iteration${env:appveyor_build_number}.$package_commit"
      Update-AppveyorBuild -Version "ponyc-$package_version-$package_iteration"
      & C:\projects\ponyc\make.ps1 build -Config $env:configuration
      $ponydir = "ponyc-${package_version}-win64-$env:configuration"
      md "$ponydir"
      md "${ponydir}\ponyc"
      md "${ponydir}\ponyc\bin"
      $builddir = "C:\projects\ponyc\build\${env:configuration}"
      copy $builddir\ponyc.* "${ponydir}\ponyc\bin"
      copy $builddir\libponyc.* "${ponydir}\ponyc\bin"
      copy $builddir\libponyrt.* "${ponydir}\ponyc\bin"
      copy $builddir\*.lib "${ponydir}\ponyc\bin"
      copy -Recurse packages "${ponydir}\packages"
      7z a -tzip "C:\projects\ponyc\${ponydir}.zip" "${ponydir}"

cache:
  - C:\projects\ponyc\build\libs -> C:\projects\ponyc\lib\CMakeFiles.txt

artifacts:
  - path: 'ponyc-*.zip'

deploy:
  # On branch `release`, deploy (and publish) artifacts
  # to the ponyc-win projects on Bintray.
  - provider: BinTray
    username: pony-buildbot-2
    api_key:
        secure: 4KgdDQLp2kX816XH27d5xdJBPlKGhYXN6ttdHTSt5qe1MVIF+/VResUstg0zuJ6m
    subject: pony-language
    repo: ponyc-win
    package: ponyc
    on:
        branch: release
        configuration: release
    publish: true

test_script:
  - ps: |
      cd C:\projects\ponyc
      & C:\projects\ponyc\make.ps1 test -Config $env:configuration
