task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64

  name: "freebsd-12-release"
  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y gmake libunwind llvm70 git

  test_script:
    - LLVM_CONFIG=llvm-config70 gmake all config=release -j3
    - LLVM_CONFIG=llvm-config70 gmake test-ci config=release

task:
  freebsd_instance:
    image: freebsd-12-0-release-amd64

  name: "freebsd-12-debug"
  depends_on:
    - freebsd-12-release

  install_script:
    - echo "FETCH_RETRY = 6" >> /usr/local/etc/pkg.conf
    - pkg update
    - pkg install -y gmake libunwind llvm70 git

  test_script:
    - LLVM_CONFIG=llvm-config70 gmake all config=debug -j3
    - LLVM_CONFIG=llvm-config70 gmake test-ci config=debug

task:
  osx_instance:
    image: high-sierra-xcode-9.4.1

  name: "macOS-release"

  install_script:
    - curl -o macports.pkg https://distfiles.macports.org/MacPorts/MacPorts-2.5.4-10.13-HighSierra.pkg
    - sudo installer -verbose -pkg macports.pkg -target /
    - sudo /opt/local/bin/port selfupdate
    - sudo /opt/local/bin/port install llvm-7.0

  test_script:
    - export LDFLAGS="-L/opt/local/lib"
    - export PATH=/usr/local/opt/llvm/bin/:$PATH
    - export CC1=clang
    - export CXX1=clang++
    - export LLVM_CONFIG=/opt/local/bin/llvm-config-mp-7.0
    - make LLVM_CONFIG="$LLVM_CONFIG" CC="$CC1" CXX="$CXX1" -j$(sysctl -n hw.ncpu) config=release all
    - make LLVM_CONFIG="$LLVM_CONFIG" CC="$CC1" CXX="$CXX1" config=release test-ci

task:
  osx_instance:
    image: high-sierra-xcode-9.4.1

  name: "macOS-debug"
  depends_on:
    - macOS-release

  install_script:
    - curl -o macports.pkg https://distfiles.macports.org/MacPorts/MacPorts-2.5.4-10.13-HighSierra.pkg
    - sudo installer -verbose -pkg macports.pkg -target /
    - sudo /opt/local/bin/port selfupdate
    - sudo /opt/local/bin/port install llvm-7.0

  test_script:
    - export LDFLAGS="-L/opt/local/lib"
    - export PATH=/usr/local/opt/llvm/bin/:$PATH
    - export CC1=clang
    - export CXX1=clang++
    - export LLVM_CONFIG=/opt/local/bin/llvm-config-mp-7.0
    - make LLVM_CONFIG="$LLVM_CONFIG" CC="$CC1" CXX="$CXX1" -j$(sysctl -n hw.ncpu) config=debug all
    - make LLVM_CONFIG="$LLVM_CONFIG" CC="$CC1" CXX="$CXX1" config=debug test-ci

task:
  name: "win64-release"
  skip: "!changesInclude('.bintray.sh', '.gitattributes', '.gitignore', 'LICENSE', 'Makefile*', '**/*.md', '**/*.txt')"

  windows_container:
    dockerfile: .ci-dockerfiles/windowsservercore/Dockerfile
    os_version: 2019

  timeout_in: 120m

  libs_cache:
    folder: build/libs
    fingerprint_script: powershell.exe -NoLogo -Command "(Get-FileHash -Path lib\CMakeLists.txt).Hash"
    populate_script: powershell.exe -NoLogo -File .\make.ps1 libs -Generator "Visual Studio 16 2019"

  config_script: powershell.exe -NoLogo -File .\make.ps1 configure -Config Release -Generator "Visual Studio 16 2019" -InstallPath "build\install\release"
  build_script: powershell.exe -NoLogo -File .\make.ps1 build -Config Release -Generator "Visual Studio 16 2019" -InstallPath "build\install\release"
  test_script: powershell.exe -NoLogo -File .\make.ps1 test -Config Release -Generator "Visual Studio 16 2019" -InstallPath "build\install\release"
  install_script: powershell.exe -NoLogo -File .\make.ps1 install -Config Release -InstallPath "build\install\release"
  package_script: powershell.exe -NoLogo -File .\make.ps1 package -Config Release -InstallPath "build\install\release" -Version date
  # upload_script: powershell.exe -NoLogo -Command "$version = (Get-Date).ToString(""""yyyyMMdd""""); & cloudsmith push raw --version $version --api-key 1cc732891a064c6542e3632a6ee281b69dbdce18 --summary """"Pony compiler"""" --description """"https://github.com/ponylang/ponyc"""" main-pony/pony-nightlies build\ponyc-x86_64-pc-windows-msvc-$version.zip

  binary_artifacts:
    path: build/*.zip


task:
  name: "win64-debug"
  skip: "!changesInclude('.bintray.sh', '.gitattributes', '.gitignore', 'LICENSE', 'Makefile*', '**/*.md', '**/*.txt')"

  windows_container:
    dockerfile: .ci-dockerfiles/windowsservercore/Dockerfile
    os_version: 2019

  timeout_in: 120m

  libs_cache:
    folder: build/libs
    fingerprint_script: powershell.exe -NoLogo -Command "(Get-FileHash -Path lib\CMakeLists.txt).Hash"
    populate_script: powershell.exe -NoLogo -File .\make.ps1 libs -Generator "Visual Studio 16 2019"

  config_script: powershell.exe -NoLogo -File .\make.ps1 configure -Config Release -Generator "Visual Studio 16 2019" -InstallPath "build\install\debug"
  build_script: powershell.exe -NoLogo -File .\make.ps1 build -Config Release -Generator "Visual Studio 16 2019" -InstallPath "build\install\debug"
  test_script: powershell.exe -NoLogo -File .\make.ps1 test -Config Release -Generator "Visual Studio 16 2019" -InstallPath "build\install\debug"
